services:
  # Frontend Vue CLI service
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    command: sh -c "npm install && npm run serve"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8080 