version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
      - ./backend/database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_KEY=base64:uenngkW3uPYTTmiB9eYAdiagf6RfwIrLluprMvZtwxs=
      - APP_URL=https://www.rrragainis.lv
      - FRONTEND_URL=https://www.rrragainis.lv
      - SANCTUM_STATEFUL_DOMAINS=www.rrragainis.lv,rrragainis.lv,46.101.117.113,[2a03:b0c0:3:f0::f2df:8000],10.114.0.2,129.212.142.67
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - PHP_UPLOAD_MAX_FILESIZE=20M
      - PHP_POST_MAX_SIZE=20M
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - VUE_APP_API_URL=https://www.rrragainis.lv/api
    expose:
      - 80

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend

volumes:
  backend_storage:
