version: '3.8'

services:
  # Frontend Vue CLI service
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '8080:8080'
    command: sh -c "npm install && npm run serve"
    environment:
      - NODE_ENV=development 